# https://taskfile.dev

version: '3'

includes:
  mkdocs: tasks/mkdocs.tasks.yml
  jenlib: tasks/jenlib.product.tasks.yml
  decks: 
    dir: decks
    taskfile: decks
  # jenconda: tasks/jenconda.product.tasks.yml
vars:

tasks:
  default:
    cmds:
      - task -l
      - echo "for more info use 'task info'"
    silent: true

  info:
    desc: Information about this dir
    silent: true
    vars:
      title: Jenlib repo actions
      content: |

        --- usefull tasklist ---
        * task info            * show info about this project
        * task mkdocs:serve    * start live docs server (serve-bg for deattached mode)
        * task ci-flow         * run ci pipeline [build, test, local_publish]
        ------------------------
        {{.title}}
        
    cmds:
      - echo '{{.content}}'
        
  ci-full:
    desc: 0-level block. build and publish. requires --force flag.
    cmds:
    - task: ci-flow
    - task: publish-flow
    status:
    - true # -prevent accidental run-

  ci-flow:
    desc: 1-level block. main entry point.
    cmds:
      - task build-stage
      - task test-stage
      - task report-stage

  build-stage:
    desc: 2-level block. build phase
    deps:
      - task: jenlib:build-jenlib
      - task: jenconda:build-jenconda
  
  jenconda:build-jenconda:
    desc: 3-level block. build jenconda docker image
    cmds:
      - task -d decks/jenkins-master build

  test-stage:
    desc: test new product
    cmds:
      - task test-e2e

  test-e2e:
    desc: Run E2E tests with build
    cmds:
      - task -d decks apply task=ci-flow targets=e2e-tests-local

  report-stage:
    desc: 2-level block. produces stam report about a build
    cmds:
      - echo "Not Yet Implemented"

  publish-flow:
    desc: 1-level block. publishes products to the world
    status: ['true']

  readme:
    desc: _
    cmds:
      - cat README.md | less

