# https://taskfile.dev

version: '3'

includes:
  mkdocs: tasks/mkdocs.tasks.yml
  # jenconda: tasks/jenconda.product.tasks.yml
  jenlib: tasks/jenlib.product.tasks.yml

vars:
  GREETING: Jenlib repo actions

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  info:
    desc: Information about this dir
    cmds:
      - |
        echo '


  ci-full-flow:
    decs: 0-level block. build and publish. requires --force
    cmds:
      - task: ci-flow
      - task: publish-flow
    status:
      - true # prevent accidental run

  ci-flow:
    desc: 1-level block. main entry point
    cmds:
      - task build-flow
      - task tests-flow
      - task report-flow

  build-flow:
    desc: 2-level block. build phase
    deps:
      - task: jenlib:build-jenlib
      - task: jenconda:build-jenconda
  
  jenconda:build-jenconda:
    desc: _
    cmds:
      - task -d decks/jenkins-master build

  tests-flow:
    desc: test new product
    cmds:
      - task test-e2e

  test-e2e:
    desc: Run E2E tests with build
    cmds:
      - task -d decks apply task=ci-flow targets=e2e-tests-local

  report-flow:
    desc: 2-level block. produces stam report about a build
    cmds:
      - echo "Not Yet Implemented"

  publish-flow:
    desc: 1-level block. publishes products to the world
    status: ['true']

  readme:
    desc: _
    cmds:
      - cat README.md | less

