# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  wait-for-event:
    desc: _
    source:
      - __tmp__/new-event/*.event.yml
    generates:
      - 
