#!/usr/local/bin/task --taskfile

# https://stackoverflow.com/questions/48379107/how-can-i-ping-other-containers-in-a-docker-network-through-their-hostname

version: "3"

vars:
  __the_taskfile_path__: infra-storage.tasks.yml
  target_dest_file: docker-compose.yaml
  
  http_infra__PORT: '28646'
  minio_infra__PORT: '29606'
  minio_console__PORT: '19001'
  network_name: local-dev-ring_test
  _repo_root_: '../..'

  _show_url_exp: |-
    ui-url--http-infra: http://localhost:{{.http_infra__PORT}}
    ui-url--minio-infra: http://localhost:{{.minio_infra__PORT}}
    ui-url--minio-ctrl: http://localhost:{{.minio_console__PORT}}

  _p_01_header: |-
    # https://stackoverflow.com/questions/48379107/how-can-i-ping-other-containers-in-a-docker-network-through-their-hostname

    version: "3.9"
    services:
  _p_02_body: |-  
    # --- services ---
      httpit.infra:
        image: pierrezemb/gostatic
        ports:
          - "{{.http_infra__PORT}}:8043"
        volumes:
          - "{{._repo_root_}}:/srv/http"
        networks:
          {{.network_name}}:
  
      minio.infra:
        # https://docs.min.io/docs/minio-docker-quickstart-guide.html
        image:   quay.io/minio/minio
        command: server /data --console-address ":19001"
        environment:
          - MINIO_ROOT_USER=minio
          - MINIO_ROOT_PASSWORD=minio123
        ports:
          - "{{.minio_infra__PORT}}:9000"
          - "{{.minio_console__PORT}}:19001"
        volumes:
          - "{{._repo_root_}}:/data"
        networks:
          {{.network_name}}:
  
  _p_14_networks: |-
    # --- networks:test ---
    networks:
      {{.network_name}}:
        external: true


tasks:
  show-urls:
    desc: shows urls of services
    silent: true
    cmds: ['echo "{{._show_url_exp}}" ']

  spin-up-flow:
    desc: _
    cmds:
      - task: spin-down
        vars:
          safe_run: 'true'
      - task: spin-up-flow.prepare
      - task: spin-up


  spin-up-flow.prepare:
    desc: _
    deps:
      - task: gen-docker-compose-file
    cmds: 
      - echo "{{.TASK}} done deps"

  spin-up:
    desc: _
    cmds: 
      - docker-compose -f {{.target_dest_file}} up  -d
  
  spin-down:
    desc: _
    vars:
      rest_suff: '{{if .safe_run}}| true{{else}} {{end}}'
    cmds: 
      - docker-compose -f {{.target_dest_file}} down {{.rest_suff}}

  gen-docker-compose-file:
    desc: _
    cmds:
      - |-
        cat << EOF > {{.target_dest_file}}
        {{._p_01_header}}
        {{._p_02_body}}
        {{._p_14_networks}}
        EOF
    sources:
      - '{{.__the_taskfile_path__}}'
    generates:
      - '{{.target_dest_file}}'





