# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true

  info:
    desc: Some Info
    cmds:
      - echo "Reach Jenkins. http://localhost:12080"
      - echo "Reach DevLab. http://localhost:12088"
    silent: true

  build:
    desc: _
    cmds:
      - docker-compose build
  stop:
    desc: _
    cmds:
      - docker-compose down || true

  run:
    desc: _
    cmds:
      - docker-compose up -d

  rerun:
    desc: _
    cmds:
      - task: stop
      - docker-compose rm
      - docker-compose up -d

  renew:
    desc: _
    cmds:
      - task: stop
      - task: build
      - task: rerun
      - task: info