# https://taskfile.dev

version: '3'

includes:
  pyinst: ../tools/pyinst.tasks.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true
# https://pypi.org/project/junit-xml//