site_name: objx/mxlibs/mxdora
# @info.todo: fill your gitlab repo URL + Name
repo_url: http://gitlab.mobileye.com/objx/mxlibs/mxdora
repo_name: objx/mxlibs/mxdora
edit_uri: edit/master/docs/

plugins:
  - mkdocstrings
  - autorefs
  - mkdocs-jupyter:
      execute: True
      kernel_name: python3
      include_source: True

  - search
  - awesome-pages:
      # to change all pages partial settings:
      #   find -name '.pages' | xargs -I% bash -c 'mv % $(dirname %)/.mkdocs.pages.yaml'
      filename: .mkdocs.pages.yaml
  # ref-uri: https://github.com/fralau/mkdocs-mermaid2-plugin/issues/10
  - macros:
      include_dir: docs
  # - mermaid2:
  #     version: 8.7.0

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - mdx_truly_sane_lists
  - mdx_math:
      use_gitlab_delimiters: True # for $`...`$ style math
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      # KEEP it commented.  Those lines break mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all

theme:
  name: material
  logo: assets/dora_bw_fat2_png_qdb_icon.ico
  favicon: assets/dora_bw_fat2_png_qdb_icon.ico
  features:
    # - navigation.expand
    # - navigation.tabs
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue grey
      # accent: teal
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
      # accent: teal

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML" # for math
  -  https://unpkg.com/mermaid@8.9.0/dist/mermaid.min.js # for mermaid graphs

nav:
  - index.md
  - release_notes.md
  - ... | **/*__release_notes.md
  - ... | structure/**/*.md
  - ...

